/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package etalon;

import java.io.File;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.lang.reflect.Method;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class Basket extends javax.swing.JFrame {
    Connect conn = new Connect();
    Connect cn = new Connect();
    Database db = new Database(cn.Conn());
    List<String> basket_arr;
    JLabel count_item;
    /**
     * Creates new form Basket
     */
    public Basket() {
        initComponents();
    }
    
    public Basket(List<String> basket_arr, JLabel count_item) {
        initComponents();
        basket_table.getColumnModel().getColumn(0).setPreferredWidth(200);
        basket_table.getColumnModel().getColumn(1).setPreferredWidth(10);
        basket_table.getColumnModel().getColumn(2).setPreferredWidth(30); 
        this.basket_arr = basket_arr;
        this.count_item = count_item;
        setBasket();
    }
    
    
    private void setBasket(){
        DefaultTableModel model = (DefaultTableModel) basket_table.getModel();
        model.setRowCount(0);
        for(int i = 0; i<basket_arr.size(); i++){
            String name = basket_arr.get(i).toString();
            String[] row = {name, "1", db.getPrice(name)};
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        basket_table = new javax.swing.JTable();
        delete = new javax.swing.JButton();
        apply = new javax.swing.JButton();

        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(203, 192, 211));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 300));

        jScrollPane1.setBackground(new java.awt.Color(243, 223, 193));

        basket_table.setBackground(new java.awt.Color(243, 223, 193));
        basket_table.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        basket_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Назва", "Кількість", "Остаточна ціна"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(basket_table);

        delete.setBackground(new java.awt.Color(210, 57, 39));
        delete.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        delete.setText("Вилучити");
        delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        apply.setBackground(new java.awt.Color(91, 142, 125));
        apply.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        apply.setText("Застосувати");
        apply.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        apply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(delete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(apply))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delete)
                    .addComponent(apply))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        int row = basket_table.getSelectedRow();
        basket_arr.remove(basket_arr.indexOf(basket_table.getModel().getValueAt(row, 0)));
        setBasket();
    }//GEN-LAST:event_deleteActionPerformed

    private void applyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyActionPerformed
        Database db = new Database(conn.Conn());
        int row = basket_table.getRowCount();
        for(int i = 0; i<row; i++){
            db.sellProduct(basket_table.getModel().getValueAt(i, 0).toString(), Integer.valueOf(basket_table.getModel().getValueAt(i, 1).toString()));
        }
        try{
            FileWriter fw = new FileWriter( "D:\\sample1.txt", true);
            for(int i=0; i<basket_table.getRowCount(); ++i)
            {
                for(int j=0; j<basket_table.getColumnCount(); ++j)
                {
                    String s = basket_table.getValueAt(i,j).toString();
                    fw.write(s);
                    if(j<basket_table.getColumnCount()-1){
                        fw.write(" - ");
                    }
                }
                fw.write("\n");
            }      
            fw.close();
            
            fw.close();
        }catch(Exception err){
            System.out.println(err);
        }
        
        super.dispose();
        Etalon.clearBasket();
        count_item.setText("0");
    }//GEN-LAST:event_applyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Basket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Basket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Basket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Basket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Basket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton apply;
    private javax.swing.JTable basket_table;
    private javax.swing.JButton delete;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
