/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package etalon;


import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Admin
 */
public class Etalon extends javax.swing.JFrame {
    Connect conn = new Connect();
    Database db = null;
    static List<String> basket_arr = new ArrayList<>();
    /**
     * Creates new form Etalon
     */
    public Etalon() {
        initComponents();
        Connection connect = conn.Conn();
        db = new Database(connect);
        info_table.getColumnModel().getColumn(0).setPreferredWidth(40);
        info_table.getColumnModel().getColumn(1).setPreferredWidth(210);
        info_table.getColumnModel().getColumn(2).setPreferredWidth(50);
        info_table.getColumnModel().getColumn(3).setPreferredWidth(50);
        info_table.getColumnModel().getColumn(4).setPreferredWidth(250);
        db.getAll(info_table);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        search = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        info_table = new javax.swing.JTable();
        add = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        add_count = new javax.swing.JButton();
        in_basket = new javax.swing.JButton();
        basket = new javax.swing.JButton();
        count_item = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(239, 211, 215));
        setForeground(java.awt.Color.white);
        setResizable(false);
        setSize(new java.awt.Dimension(700, 500));

        jPanel1.setBackground(new java.awt.Color(203, 192, 211));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 500));

        search.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        search.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        search.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(142, 154, 175), 2, true));
        search.setPreferredSize(new java.awt.Dimension(350, 30));
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchKeyPressed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(243, 223, 193));

        info_table.setBackground(new java.awt.Color(243, 223, 193));
        info_table.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        info_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Назва", "Кількість", "Ціна", "Розташування"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        info_table.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setViewportView(info_table);

        add.setBackground(new java.awt.Color(169, 210, 213));
        add.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        add.setText("Додати новий");
        add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        edit.setBackground(new java.awt.Color(242, 158, 76));
        edit.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        edit.setText("Змінити");
        edit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        add_count.setBackground(new java.awt.Color(4, 139, 168));
        add_count.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        add_count.setText("Додати кількість");
        add_count.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_count.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_countActionPerformed(evt);
            }
        });

        in_basket.setBackground(new java.awt.Color(239, 244, 90));
        in_basket.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        in_basket.setText("В корзину");
        in_basket.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        in_basket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_basketActionPerformed(evt);
            }
        });

        basket.setBackground(new java.awt.Color(221, 190, 168));
        basket.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        basket.setText("Корзина");
        basket.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        basket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basketActionPerformed(evt);
            }
        });

        count_item.setBackground(new java.awt.Color(254, 255, 165));
        count_item.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        count_item.setText("0");
        count_item.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(count_item)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(add)
                            .addGap(20, 20, 20)
                            .addComponent(edit)
                            .addGap(20, 20, 20)
                            .addComponent(add_count)
                            .addGap(20, 20, 20)
                            .addComponent(in_basket)
                            .addGap(20, 20, 20)
                            .addComponent(basket))))
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(count_item)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add)
                    .addComponent(add_count)
                    .addComponent(basket)
                    .addComponent(in_basket)
                    .addComponent(edit))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
            Product pr = new Product(info_table, "add");
            pr.show();
    }//GEN-LAST:event_addActionPerformed

    private void searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyPressed
        db.search(search, info_table);
    }//GEN-LAST:event_searchKeyPressed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        int row = info_table.getSelectedRow();
        Product pr = new Product(info_table, "edit", row);
        pr.show();
    }//GEN-LAST:event_editActionPerformed

    private void add_countActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_countActionPerformed
        int row = info_table.getSelectedRow();
        int select_id = Integer.parseInt(info_table.getModel().getValueAt(row, 0).toString());
        int select_count = Integer.parseInt(info_table.getModel().getValueAt(row, 2).toString());
        db.addCount(select_id, select_count+1);
        info_table.getModel().setValueAt(select_count+1, row, 2);
        
    }//GEN-LAST:event_add_countActionPerformed

    private void in_basketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_basketActionPerformed
        int row = info_table.getSelectedRow();
        basket_arr.add(info_table.getModel().getValueAt(row, 1).toString());
        count_item.setText(" "+basket_arr.size()+" ");
    }//GEN-LAST:event_in_basketActionPerformed

    private void basketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basketActionPerformed
        Basket bs = new Basket(basket_arr, count_item);
        bs.show();
    }//GEN-LAST:event_basketActionPerformed

    /**
     *
     */
    public static void clearBasket(){
        basket_arr.clear();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Etalon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Etalon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Etalon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Etalon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Etalon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton add_count;
    private javax.swing.JButton basket;
    private javax.swing.JLabel count_item;
    private javax.swing.JButton edit;
    private javax.swing.JButton in_basket;
    private javax.swing.JTable info_table;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField search;
    // End of variables declaration//GEN-END:variables
}
